export const lhConfig = {
    auto: {
        states: [
            { value: 'AL', label: 'Alabama' },
            { value: 'AK', label: 'Alaska' },
            { value: 'AZ', label: 'Arizona' },
            { value: 'AR', label: 'Arkansas' },
            { value: 'CA', label: 'California' },
            { value: 'CO', label: 'Colorado' },
            { value: 'CT', label: 'Connecticut' },
            { value: 'DC', label: 'D.C.' },
            { value: 'DE', label: 'Delaware' },
            { value: 'FL', label: 'Florida' },
            { value: 'GA', label: 'Georgia' },
            { value: 'HI', label: 'Hawaii' },
            { value: 'ID', label: 'Idaho' },
            { value: 'IL', label: 'Illinois' },
            { value: 'IN', label: 'Indiana' },
            { value: 'IA', label: 'Iowa' },
            { value: 'KS', label: 'Kansas' },
            { value: 'KY', label: 'Kentucky' },
            { value: 'LA', label: 'Louisiana' },
            { value: 'ME', label: 'Maine' },
            { value: 'MD', label: 'Maryland' },
            { value: 'MA', label: 'Massachusetts' },
            { value: 'MI', label: 'Michigan' },
            { value: 'MN', label: 'Minnesota' },
            { value: 'MS', label: 'Mississippi' },
            { value: 'MO', label: 'Missouri' },
            { value: 'MT', label: 'Montana' },
            { value: 'NE', label: 'Nebraska' },
            { value: 'NV', label: 'Nevada' },
            { value: 'NH', label: 'New Hampshire' },
            { value: 'NJ', label: 'New Jersey' },
            { value: 'NM', label: 'New Mexico' },
            { value: 'NY', label: 'New York' },
            { value: 'NC', label: 'North Carolina' },
            { value: 'ND', label: 'North Dakota' },
            { value: 'OH', label: 'Ohio' },
            { value: 'OK', label: 'Oklahoma' },
            { value: 'OR', label: 'Oregon' },
            { value: 'PA', label: 'Pennsylvania' },
            { value: 'RI', label: 'Rhode Island' },
            { value: 'SC', label: 'South Carolina' },
            { value: 'SD', label: 'South Dakota' },
            { value: 'TN', label: 'Tennessee' },
            { value: 'TX', label: 'Texas' },
            { value: 'UT', label: 'Utah' },
            { value: 'VT', label: 'Vermont' },
            { value: 'VA', label: 'Virginia' },
            { value: 'WA', label: 'Washington' },
            { value: 'WV', label: 'West Virginia' },
            { value: 'WI', label: 'Wisconsin' },
            { value: 'WY', label: 'Wyoming' },
            { value: 'AE', label: 'AE' },
            { value: 'AP', label: 'AP' },
            { value: 'AA', label: 'AA' }
        ],
        lossCauses: [
            { value: 'All Other', label: 'All Other'},
            { value: 'Animal Collision - Comprehensive', label: 'Animal Collision - Comprehensive'},
            { value: 'Death Benefits', label: 'Death Benefits'},
            { value: 'Explosion', label: 'Explosion'},
            { value: 'Falling Object', label: 'Falling Object'},
            { value: 'Fire - Engine Related', label: 'Fire - Engine Related'},
            { value: 'Fire - Other', label: 'Fire - Other'},
            { value: 'Flood', label: 'Flood'},
            { value: 'Glass Breakage', label: 'Glass Breakage'},
            { value: 'Loss of Income PIP', label: 'Loss of Income PIP'},
            { value: 'Multi Vehicle Accident', label: 'Multi Vehicle Accident'},
            { value: 'Pedestrian - Bicycle', label: 'Pedestrian - Bicycle'},
            { value: 'Roadside Assistance', label: 'Roadside Assistance'},
            { value: 'Single Vehicle Accident', label: 'Single Vehicle Accident'},
            { value: 'Theft', label: 'Theft'},
            { value: 'Theft from Unattended Auto', label: 'Theft from Unattended Auto'},
            { value: 'Vandalism and Malicious Mischief', label: 'Vandalism and Malicious Mischief'},
            { value: 'Windshield/Glass Breakage Only', label: 'Windshield / Glass Breakage Only'},
            { value: 'Windstorm and Hail', label: 'Windstorm and Hail'}            
        ],
        atFaultCdOptions : [
            { value: 'At Fault', label: 'At Fault' },
            { value: 'Not At Fault', label: 'Not At Fault' },
            { value: 'Unknown', label: 'Unknown' }
        ],
        typeCdOptions: [
            { value: 'Auto', label: 'Auto' },
            { value: 'Motorcycle', label: 'Motorcycle' },
            { value: 'Farm', label: 'Farm' }
        ],
        driverNameOptions: [
            { value: "Parked", label: "Parked" },
            { value: "PermissiveUse", label: "Permissive Use" },
            { value: "NonPermissiveUse", label: "Non-Permissive Use" },
            { value: "None", label: "None" }
        ]
    }
}