export type DTOLossHistory = {
    LossHistoryNumber?: string,
    LossDt?: string,
    LossCauseCd?: string,
    ClaimNumber?: string,
    ClaimStatusCd?: string,
    CatastropheNumber?: string,
    CarrierName?: string,
    TypeCd?: string,
    PolicyNumber?: string,
    LossAmt?: string,
    PaidAmt?: string,
    VehIdentificationNumber?: string,
    AtFaultCd?: string,
    DriverName?: string,
    DriverLicensedStateProvCd?: string,
    DriverLicenseNumber?: string,
    Comment?: string,
    LossDesc?: string,
    id?: string,
    StatusCd?: string,
    SourceCd?: string,
    PolicyTypeCd?: string
}